### ISSUE TITLE
[README] What to download | Testing the CI

### ISSUE THREAD

**Issue by SIMULATAN** [MC-Stalker/mcstalker-utility-mod#11]
Please don't use any versions of type 0.x.x - those are only testing versions. (Testing the CI - they are behind in terms of the mod!)
The versions you should be using are 1.0.2+

For anyone that downloaded the version 1.0.3 **before** the 25th of january 2022, please use version 1.0.2, i messed up the versions a bit 😅 
Yep, version 1.0.2 is indeed newer than 1.0.3 (at least atm)

**Comment by Vitalasy** [comment]
> Please don't use any versions of type 0.x.x - those are only testing versions. The versions you should be using are 1.0.2+
> 
> For anyone that downloaded the version 1.0.3 **before** the 25th of january 2022, please use version 1.0.2, i messed up the versions a bit 😅 Yep, version 1.0.2 is indeed newer than 1.0.3 (at least atm)

but the bugs should be reported for 0.x.x version right?

**Comment by TheOnlyWayUp** [comment]
> > Please don't use any versions of type 0.x.x - those are only testing versions. The versions you should be using are 1.0.2+
> > For anyone that downloaded the version 1.0.3 **before** the 25th of january 2022, please use version 1.0.2, i messed up the versions a bit 😅 Yep, version 1.0.2 is indeed newer than 1.0.3 (at least atm)
> 
> but the bugs should be reported for 0.x.x version right?

0.x.x versions are testing versions which are not maintained, nor are actually functional. Please use version 1.0.2 for all bug reports, if you're not using that version, you're bound to face some issues. 1.0.2 is a maintained version of the mod and we accept bug reports for that version only at the moment.

**Comment by SIMULATAN** [comment]
Nope, everything is 1.x.x (at the moment 1.0.2)
0.x.x should be ignored completely, those are builds of old versions with the new CI

**Comment by Vitalasy** [comment]
> Nope, everything is 1.x.x (at the moment 1.0.2) 0.x.x should be ignored completely, those are builds of old versions with the new CI

alright 👍

**Comment by TheOnlyWayUp** [comment]
@SIMULATAN Do we keep this issue open? Either way, it'll stay pinned.

**Comment by SIMULATAN** [comment]
Idc
