### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Vitalasy** [MC-Stalker/mcstalker-utility-mod#4]
https://paste.ee/p/OwW62 <--- Log

**Comment by Colourblindness** [comment]
cope about it!!!!!!

**Comment by TheOnlyWayUp** [comment]
@Colourblindness Either be useful, or you'll be blocked by this account. Essentially blocking you from creating issues, commenting, or performing a variety of actions. You can read the full consequences of getting blocked [here[(https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization).

**Comment by SIMULATAN** [comment]
@Vitalasy I think I already know why that happens, I'll be working on a fix in a sec

**Comment by Vitalasy** [comment]
> @Vitalasy I think I already know why that happens, I'll be working on a fix in a sec

thank you!

**Comment by SIMULATAN** [comment]
@Vitalasy did you download a precompiled build or did you build it yourself?

**Comment by Vitalasy** [comment]
> @Vitalasy did you download a precompiled build or did you build it yourself?

precompiled

**Comment by Vitalasy** [comment]
17,zulu,latest-win

**Comment by SIMULATAN** [comment]
Which jar did you use? The mcstalker-x.x.x.jar is the right one

**Comment by Vitalasy** [comment]
> Which jar did you use? The mcstalker-x.x.x.jar is the right one

1st i tried with -all then the mcstalker-x.x.x same crash

**Comment by Vitalasy** [comment]
issue solved.

**Comment by SIMULATAN** [comment]
For the record; the reason was that he used the -all version of the mod which is a non-remapped version and thus crashes. I'll rename the jar soon™
