### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Vitalasy** [MC-Stalker/mcstalker-utility-mod#7]
https://paste.ee/p/F4in5 crash when trying to ping a server in mcstalker section
also there  is a random crash when editing a module's settings but is really random.

**Comment by Vitalasy** [comment]
by module's settings i mean meteor client's modules' settings

**Comment by SIMULATAN** [comment]
The module settings crash can't be fixed by us
About the server list rendering thingy, well, I'll look into it as soon as I can but it might take a bit of time because I'm not @ my main machine atm

**Comment by Vitalasy** [comment]
> in the meantime, could you maybe install [Not enough Crashes](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes), it might only log a error and keep you in the game and especially it'll deobfuscate the stack trace which helps me to debug the issue on my trash laptop

i will look into it 👍

**Comment by Vitalasy** [comment]
https://bytebin.lucko.me/YSlhYxyWAJ

**Comment by SIMULATAN** [comment]
Probably fixed in https://github.com/MC-Stalker/mcstalker-utility-mod/commit/1670188828facbd3e9896a5a8cc02538fa331b0d
