### ISSUE TITLE
Ban evade ain't working

### ISSUE THREAD

**Issue by Savvakos7** [MC-Stalker/mcstalker-utility-mod#9]
Fix ban evade or completely remove it

**Comment by SIMULATAN** [comment]
Ban evade is supposed to be a central API that is getting changed by clients, ask client devs to implement it.
Also, "it doesn't work" is kinda vague, it only changes your username to a cracked one so no shit it doesn't work on online servers

**Comment by Savvakos7** [comment]
My boy all I know is that it's useless, everything else is yours to fix😂

**Comment by SIMULATAN** [comment]
It's not useless but rather only usable to an extend.

**Comment by Savvakos7** [comment]
So it can ONLY work on cracked servers?

**Comment by SIMULATAN** [comment]
yep, that's it's purpose

**Comment by CyberLykan** [comment]
bruh moment
